#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DatawedgeIntentExample3.Resource", IsApplication=true)]

namespace DatawedgeIntentExample3
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040001
			public const int txtScanData = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int txtScanDecoder = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int txtScanScource = 2130968576;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int Main = 2130837504;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030001
			public const int activity_intent_filter_action = 2130903041;
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			// aapt resource value: 0x7f030004
			public const int datawedge_intent_key_data = 2130903044;
			
			// aapt resource value: 0x7f030007
			public const int datawedge_intent_key_data_legacy = 2130903047;
			
			// aapt resource value: 0x7f030003
			public const int datawedge_intent_key_label_type = 2130903043;
			
			// aapt resource value: 0x7f030006
			public const int datawedge_intent_key_label_type_legacy = 2130903046;
			
			// aapt resource value: 0x7f030002
			public const int datawedge_intent_key_source = 2130903042;
			
			// aapt resource value: 0x7f030005
			public const int datawedge_intent_key_source_legacy = 2130903045;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
